# Site settings
title: Asal Nassiri
description: One of a kind website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Asal Nassiri
user_description: Bicycle rights? Can you pickle that? These are some of my very wild thoughts. Please let me know if you tend to think about some of the same things.
user_title: Explorer
email: asalnassiri@gmail.com
twitter_username: asalnassiri
github_username: asalnassiri
gplus_username: asalnassiri

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
